In [1]:
import numpy as np
from numpy import load

In [2]:
data = load('md17_naphthalene.npz')
lst = data.files
for item in lst:
    print(item)
    print(data[item])

E
[[-241923.48033637]
 [-241923.42291586]
 [-241922.46431141]
 ...
 [-241896.07774737]
 [-241896.10727407]
 [-241896.16579755]]
name
b'naphthalene'
F
[[[ 1.77166443e+00 -3.11529186e+00  3.34271303e-01]
  [-1.48718503e+01 -9.68218773e+00 -7.01735675e-02]
  [-1.48717811e+01  9.68237221e+00 -7.96349985e-02]
  ...
  [ 8.94517895e+00  4.12745674e+00 -9.07374040e-03]
  [ 8.94531731e+00 -4.12761817e+00  1.74190735e-02]
  [-1.94139783e+00 -9.58849353e+00  4.47234734e-31]]

 [[-6.39687191e+00 -1.45135155e+01  3.33676346e+00]
  [-1.27040391e+01 -9.95923478e+00  1.43578812e-01]
  [-2.48366888e+01  4.26300548e+00  2.68390190e-01]
  ...
  [ 4.07610135e+00  3.14031234e+00  1.04578687e+00]
  [ 6.71399784e+00 -2.71351138e+00 -3.39524451e-01]
  [-2.60323679e+00 -2.56938420e+00 -5.09728282e-12]]

 [[-1.46365425e+01 -2.49478396e+01  6.84398904e+00]
  [-1.08385259e+01 -1.03629754e+01  3.99877999e-01]
  [-3.48817772e+01 -9.88387355e-01  8.02698499e-01]
  ...
  [-1.11757605e+00  2.04886828e+00  2.20597845e+

In [3]:
print(lst)

['E', 'name', 'F', 'theory', 'R', 'z', 'type', 'md5']


In [5]:
data['E'][0]

array([-241923.48033637])

In [5]:
import numpy as np
f = open("naphthalene.xyz","r")
for i in range(326250):
    name = "napthalenegeometries/C10H8_%06d.pdb.xyz" % (i+1)
    outf = open(name,"w")
    for j in range(20):
        s=f.readline()
        outf.writelines(s)
    outf.close()    
f.close()


napthalenegeometries/C10H8_000001.pdb.xyz


UnsupportedOperation: not readable

In [ ]:
import qml

# Create the compound object mol from the file qm7/0001.xyz which happens to be methane
mol = qml.Compound(xyz="/0001.xyz")

# Generate and print a coulomb matrix for compound with 5 atoms
mol.generate_coulomb_matrix(size=18, sorting="row-norm")
print(mol.representation)